#!/bin/sh

finished=0

while [ $finished -eq 0 ]
do
    output=`yncactl list $1`
    header="`echo -e "$output" | head -n 1`"
    rest="`echo -e "$output" | tail -n +2`"

    choice=`echo -e "$rest" | rofi -dmenu -p "$header: " -width 80 -location 2 -bg "#000000" -fg "#FFFFFF" -hlbg "#285500" -opacity "90"`

    if [ -n "$choice" ]; then
        choose=`yncactl list $1 $choice`
        chosen_type=`echo "$choose" | awk -F':' '{print $1}'`
        echo $chosen_type
        if [ "$chosen_type" = "Item" ]; then
            let finished=1
        fi
    else
        let finished=1
    fi
done
